### PR TITLE
modified the navbar and shifted submit button a bit

### PR DESCRIPTION
**Pull request by radzhiv25**
Anymore changes required please let me know i will try to do it ASAP

### CODE REVIEW

**Comment by radzhiv25** [comment]
@Skarlso please update

**Comment by Skarlso** [comment]
Will take a look in about an hour.

**Comment by radzhiv25** [comment]
> Will take a look in about an hour.

Sorry by mistake I have created a wrong pull request 
It was not updated with respect to the repository

**Comment by Skarlso** [comment]
No worries. :)

**Pull request closed without merging**
