### PR TITLE
update go packages

### PR DESCRIPTION
**Pull request by PlayMTL**
This PR updates the used go packages.

I tested the updates with CRD from Logging-Operator: https://raw.githubusercontent.com/kube-logging/logging-operator/master/charts/logging-operator/crds/logging.banzaicloud.io_clusterflows.yaml

### CODE REVIEW

**Comment by Skarlso** [comment]
Nice, thanks for the update. :)

**Comment by PlayMTL** [comment]
Thanks for the merge, are you able to build a new patchversion as release? :)

**Comment by Skarlso** [comment]
Will do :)

**Comment by Skarlso** [comment]
Done. :)

**Pull request merged**
